# Generated by Django 2.2.5 on 2020-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
