# Generated by Django 2.2.5 on 2020-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200518_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
