# Generated by Django 2.0 on 2020-05-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_users'),
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=100)),
                ('Cover', models.CharField(max_length=100)),
                ('StoryLine', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.Movies')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
    ]
